apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment   # Change to your deployment name
  labels:
    tier: backend           # Change to your app label
spec:
  replicas: 3               # How many pod replicas you want
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.0  # Replace with your container image
